name: Refresh Snapshots List

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  workflow_dispatch:

jobs:
  refresh_snapshots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Refresh snapshot_data.json
      run: |
        echo "Updating lastRefreshed in snapshot_data.json with the current UTC timestamp..."
        node -e "
        const fs = require('fs');
        const path = './snapshot_data.json';
        let data = {};
        if (fs.existsSync(path)) {
          data = JSON.parse(fs.readFileSync(path, 'utf8'));
        }
        data.meta = data.meta || {};
        data.meta.lastRefreshed = new Date().toISOString();
        fs.writeFileSync(path, JSON.stringify(data, null, 2));
        "

    - name: Commit and Push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add snapshot_data.json
        git commit -m "Update lastRefreshed in snapshot_data.json"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

